Replacing 'create' trigger for 'push' in Step 0
skills/code-with-codespaces pull request #86
Opened 2024-04-12 20:41 UTC by RelicCornhusk

The 'create' trigger does not get picked up once you create a repository from a template. Instead, the 'push' trigger should be used here for this purpose.

### Summary

When following the steps in the template repository and creating a new repository from template, the Github Actions Workflow for 'Step 0: Welcome' does not get triggered. This is because the trigger 'create' being used does not trigger the workflow on this type of event. The only exception to this is if the user creates the template repository with the checkbox 'Include all branches' checked. This counts as a branch creation and thus triggers the workflow, however this is not the default option and should not be expected of users.

### Changes

Using the `push` trigger. As per [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push), the `push`trigger _runs your workflow when you push a commit or tag, or when you create a repository from a template._

Closes:

### Task list

- [ ] For workflow changes, I have verified the Actions workflows function as expected.
- [ ] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2024-04-15 05:32 UTC, sinsukehlab requested changes
From [skills/template-template](/skills/template-template)

```yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
```

2024-04-15 13:39 UTC, sinsukehlab approved these changes

2024-04-30 20:28 UTC, heiskr requested changes
Matches introduction to GitHub

2024-04-30 20:29 UTC, heiskr approved these changes
Buttons 😂

2024-04-30 20:29 UTC, merged

2024-12-04 08:32 UTC, Nomankhan1144 commented
workwithaditimistry@gmail.com

2025-01-23 08:29 UTC, CosmicJesterX reviewed
pls review